// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ShapeInterference_SequenceOfInterfObj.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _ShapeInterference_InterfObj_HeaderFile
#include <ShapeInterference_InterfObj.hxx>
#endif
#ifndef _ShapeInterference_SequenceNodeOfSequenceOfInterfObj_HeaderFile
#include <ShapeInterference_SequenceNodeOfSequenceOfInterfObj.hxx>
#endif
 

#define SeqItem Handle_ShapeInterference_InterfObj
#define SeqItem_hxx <ShapeInterference_InterfObj.hxx>
#define TCollection_SequenceNode ShapeInterference_SequenceNodeOfSequenceOfInterfObj
#define TCollection_SequenceNode_hxx <ShapeInterference_SequenceNodeOfSequenceOfInterfObj.hxx>
#define Handle_TCollection_SequenceNode Handle_ShapeInterference_SequenceNodeOfSequenceOfInterfObj
#define TCollection_SequenceNode_Type_() ShapeInterference_SequenceNodeOfSequenceOfInterfObj_Type_()
#define TCollection_Sequence ShapeInterference_SequenceOfInterfObj
#define TCollection_Sequence_hxx <ShapeInterference_SequenceOfInterfObj.hxx>
#include <TCollection_Sequence.gxx>

