// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ShapeInterference_SequenceNodeOfSequenceOfInterfObj.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _ShapeInterference_InterfObj_HeaderFile
#include <ShapeInterference_InterfObj.hxx>
#endif
#ifndef _ShapeInterference_SequenceOfInterfObj_HeaderFile
#include <ShapeInterference_SequenceOfInterfObj.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(ShapeInterference_SequenceNodeOfSequenceOfInterfObj)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(ShapeInterference_SequenceNodeOfSequenceOfInterfObj)


IMPLEMENT_DOWNCAST(ShapeInterference_SequenceNodeOfSequenceOfInterfObj,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(ShapeInterference_SequenceNodeOfSequenceOfInterfObj)


#define SeqItem Handle_ShapeInterference_InterfObj
#define SeqItem_hxx <ShapeInterference_InterfObj.hxx>
#define TCollection_SequenceNode ShapeInterference_SequenceNodeOfSequenceOfInterfObj
#define TCollection_SequenceNode_hxx <ShapeInterference_SequenceNodeOfSequenceOfInterfObj.hxx>
#define Handle_TCollection_SequenceNode Handle_ShapeInterference_SequenceNodeOfSequenceOfInterfObj
#define TCollection_SequenceNode_Type_() ShapeInterference_SequenceNodeOfSequenceOfInterfObj_Type_()
#define TCollection_Sequence ShapeInterference_SequenceOfInterfObj
#define TCollection_Sequence_hxx <ShapeInterference_SequenceOfInterfObj.hxx>
#include <TCollection_SequenceNode.gxx>

