// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapeInterference_InterfObj_HeaderFile
#define _ShapeInterference_InterfObj_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_ShapeInterference_InterfObj_HeaderFile
#include <Handle_ShapeInterference_InterfObj.hxx>
#endif

#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
#ifndef _ShapeInterference_TypeOfInterf_HeaderFile
#include <ShapeInterference_TypeOfInterf.hxx>
#endif
class TopoDS_Shape;



class ShapeInterference_InterfObj : public MMgt_TShared {

public:

  //! Empty constructor. <br>
  Standard_EXPORT   ShapeInterference_InterfObj();
  //! Stores the section result. <br>
  Standard_EXPORT     void SetSection(const TopoDS_Shape& aSectionResult) ;
  //! Returns the interference elementary <br>
//!          object's type : TOI_COLLISION, or TOI_TGCY. <br>
  Standard_EXPORT   virtual  ShapeInterference_TypeOfInterf GetInterfType() const;
  //! Get field mySection. <br>
  Standard_EXPORT     TopoDS_Shape GetSection() const;




  DEFINE_STANDARD_RTTI(ShapeInterference_InterfObj)

protected:




private: 


TopoDS_Shape mySection;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
