// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapePlacement_TypeOfAxisConstraint_HeaderFile
#define _ShapePlacement_TypeOfAxisConstraint_HeaderFile

//! Type of a Constraint. <br>
enum ShapePlacement_TypeOfAxisConstraint {
ShapePlacement_AXIS,
ShapePlacement_NONE
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
