// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapeInterference_Collision_HeaderFile
#define _ShapeInterference_Collision_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_ShapeInterference_Collision_HeaderFile
#include <Handle_ShapeInterference_Collision.hxx>
#endif

#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _ShapeInterference_InterfObj_HeaderFile
#include <ShapeInterference_InterfObj.hxx>
#endif
#ifndef _ShapeInterference_TypeOfInterf_HeaderFile
#include <ShapeInterference_TypeOfInterf.hxx>
#endif
class TopoDS_Shape;



class ShapeInterference_Collision : public ShapeInterference_InterfObj {

public:

  //! Empty constructor. <br>
  Standard_EXPORT   ShapeInterference_Collision();
  //! Stores the common result. <br>
  Standard_EXPORT     void SetCommon(const TopoDS_Shape& aCommonResult) ;
  //! Returns ShapeInterference_TOI_COLISION. <br>
  Standard_EXPORT   virtual  ShapeInterference_TypeOfInterf GetInterfType() const;
  //! Get field myCommon. <br>
  Standard_EXPORT     TopoDS_Shape GetCommon() const;




  DEFINE_STANDARD_RTTI(ShapeInterference_Collision)

protected:




private: 


TopoDS_Shape myCommon;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
