// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapePlacement_ListIteratorOfListOfConstraint_HeaderFile
#define _ShapePlacement_ListIteratorOfListOfConstraint_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_ShapePlacement_ListNodeOfListOfConstraint_HeaderFile
#include <Handle_ShapePlacement_ListNodeOfListOfConstraint.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoMoreObject;
class Standard_NoSuchObject;
class ShapePlacement_ListOfConstraint;
class ShapePlacement_Constraint;
class ShapePlacement_ListNodeOfListOfConstraint;



class ShapePlacement_ListIteratorOfListOfConstraint  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   ShapePlacement_ListIteratorOfListOfConstraint();
  
  Standard_EXPORT   ShapePlacement_ListIteratorOfListOfConstraint(const ShapePlacement_ListOfConstraint& L);
  
  Standard_EXPORT     void Initialize(const ShapePlacement_ListOfConstraint& L) ;
  
        Standard_Boolean More() const;
  
  Standard_EXPORT     void Next() ;
  
  Standard_EXPORT     ShapePlacement_Constraint& Value() const;


friend class ShapePlacement_ListOfConstraint;



protected:





private:



Standard_Address current;
Standard_Address previous;


};

#define Item ShapePlacement_Constraint
#define Item_hxx <ShapePlacement_Constraint.hxx>
#define TCollection_ListNode ShapePlacement_ListNodeOfListOfConstraint
#define TCollection_ListNode_hxx <ShapePlacement_ListNodeOfListOfConstraint.hxx>
#define TCollection_ListIterator ShapePlacement_ListIteratorOfListOfConstraint
#define TCollection_ListIterator_hxx <ShapePlacement_ListIteratorOfListOfConstraint.hxx>
#define Handle_TCollection_ListNode Handle_ShapePlacement_ListNodeOfListOfConstraint
#define TCollection_ListNode_Type_() ShapePlacement_ListNodeOfListOfConstraint_Type_()
#define TCollection_List ShapePlacement_ListOfConstraint
#define TCollection_List_hxx <ShapePlacement_ListOfConstraint.hxx>

#include <TCollection_ListIterator.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
