// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapePlacement_ListNodeOfListOfConstraint_HeaderFile
#define _ShapePlacement_ListNodeOfListOfConstraint_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_ShapePlacement_ListNodeOfListOfConstraint_HeaderFile
#include <Handle_ShapePlacement_ListNodeOfListOfConstraint.hxx>
#endif

#ifndef _ShapePlacement_Constraint_HeaderFile
#include <ShapePlacement_Constraint.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class ShapePlacement_Constraint;
class ShapePlacement_ListOfConstraint;
class ShapePlacement_ListIteratorOfListOfConstraint;



class ShapePlacement_ListNodeOfListOfConstraint : public TCollection_MapNode {

public:

  
      ShapePlacement_ListNodeOfListOfConstraint(const ShapePlacement_Constraint& I,const TCollection_MapNodePtr& n);
  
        ShapePlacement_Constraint& Value() const;




  DEFINE_STANDARD_RTTI(ShapePlacement_ListNodeOfListOfConstraint)

protected:




private: 


ShapePlacement_Constraint myValue;


};

#define Item ShapePlacement_Constraint
#define Item_hxx <ShapePlacement_Constraint.hxx>
#define TCollection_ListNode ShapePlacement_ListNodeOfListOfConstraint
#define TCollection_ListNode_hxx <ShapePlacement_ListNodeOfListOfConstraint.hxx>
#define TCollection_ListIterator ShapePlacement_ListIteratorOfListOfConstraint
#define TCollection_ListIterator_hxx <ShapePlacement_ListIteratorOfListOfConstraint.hxx>
#define Handle_TCollection_ListNode Handle_ShapePlacement_ListNodeOfListOfConstraint
#define TCollection_ListNode_Type_() ShapePlacement_ListNodeOfListOfConstraint_Type_()
#define TCollection_List ShapePlacement_ListOfConstraint
#define TCollection_List_hxx <ShapePlacement_ListOfConstraint.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
