// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapeInterference_TypeOfInterf_HeaderFile
#define _ShapeInterference_TypeOfInterf_HeaderFile


enum ShapeInterference_TypeOfInterf {
ShapeInterference_TOI_TGCY,
ShapeInterference_TOI_COLLISION
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
