// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapeInterference_SequenceOfInterfObj_HeaderFile
#define _ShapeInterference_SequenceOfInterfObj_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_ShapeInterference_InterfObj_HeaderFile
#include <Handle_ShapeInterference_InterfObj.hxx>
#endif
#ifndef _Handle_ShapeInterference_SequenceNodeOfSequenceOfInterfObj_HeaderFile
#include <Handle_ShapeInterference_SequenceNodeOfSequenceOfInterfObj.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class ShapeInterference_InterfObj;
class ShapeInterference_SequenceNodeOfSequenceOfInterfObj;



class ShapeInterference_SequenceOfInterfObj  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      ShapeInterference_SequenceOfInterfObj();
  
  Standard_EXPORT     void Clear() ;
~ShapeInterference_SequenceOfInterfObj()
{
  Clear();
}
  
  Standard_EXPORT    const ShapeInterference_SequenceOfInterfObj& Assign(const ShapeInterference_SequenceOfInterfObj& Other) ;
   const ShapeInterference_SequenceOfInterfObj& operator =(const ShapeInterference_SequenceOfInterfObj& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const Handle(ShapeInterference_InterfObj)& T) ;
  
        void Append(ShapeInterference_SequenceOfInterfObj& S) ;
  
  Standard_EXPORT     void Prepend(const Handle(ShapeInterference_InterfObj)& T) ;
  
        void Prepend(ShapeInterference_SequenceOfInterfObj& S) ;
  
        void InsertBefore(const Standard_Integer Index,const Handle(ShapeInterference_InterfObj)& T) ;
  
        void InsertBefore(const Standard_Integer Index,ShapeInterference_SequenceOfInterfObj& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const Handle(ShapeInterference_InterfObj)& T) ;
  
        void InsertAfter(const Standard_Integer Index,ShapeInterference_SequenceOfInterfObj& S) ;
  
  Standard_EXPORT    const Handle_ShapeInterference_InterfObj& First() const;
  
  Standard_EXPORT    const Handle_ShapeInterference_InterfObj& Last() const;
  
        void Split(const Standard_Integer Index,ShapeInterference_SequenceOfInterfObj& Sub) ;
  
  Standard_EXPORT    const Handle_ShapeInterference_InterfObj& Value(const Standard_Integer Index) const;
   const Handle_ShapeInterference_InterfObj& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const Handle(ShapeInterference_InterfObj)& I) ;
  
  Standard_EXPORT     Handle_ShapeInterference_InterfObj& ChangeValue(const Standard_Integer Index) ;
    Handle_ShapeInterference_InterfObj& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   ShapeInterference_SequenceOfInterfObj(const ShapeInterference_SequenceOfInterfObj& Other);




};

#define SeqItem Handle_ShapeInterference_InterfObj
#define SeqItem_hxx <ShapeInterference_InterfObj.hxx>
#define TCollection_SequenceNode ShapeInterference_SequenceNodeOfSequenceOfInterfObj
#define TCollection_SequenceNode_hxx <ShapeInterference_SequenceNodeOfSequenceOfInterfObj.hxx>
#define Handle_TCollection_SequenceNode Handle_ShapeInterference_SequenceNodeOfSequenceOfInterfObj
#define TCollection_SequenceNode_Type_() ShapeInterference_SequenceNodeOfSequenceOfInterfObj_Type_()
#define TCollection_Sequence ShapeInterference_SequenceOfInterfObj
#define TCollection_Sequence_hxx <ShapeInterference_SequenceOfInterfObj.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
