// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapeInterference_TypeOfTgcy_HeaderFile
#define _ShapeInterference_TypeOfTgcy_HeaderFile


enum ShapeInterference_TypeOfTgcy {
ShapeInterference_TOT_TGCYONEDGE,
ShapeInterference_TOT_TGCYONFACE
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
