// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapePlacement_ListOfConstraint_HeaderFile
#define _ShapePlacement_ListOfConstraint_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_ShapePlacement_ListNodeOfListOfConstraint_HeaderFile
#include <Handle_ShapePlacement_ListNodeOfListOfConstraint.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class ShapePlacement_ListIteratorOfListOfConstraint;
class ShapePlacement_Constraint;
class ShapePlacement_ListNodeOfListOfConstraint;



class ShapePlacement_ListOfConstraint  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   ShapePlacement_ListOfConstraint();
  
  Standard_EXPORT     void Assign(const ShapePlacement_ListOfConstraint& Other) ;
    void operator=(const ShapePlacement_ListOfConstraint& Other) 
{
  Assign(Other);
}
  
  Standard_EXPORT     Standard_Integer Extent() const;
  
  Standard_EXPORT     void Clear() ;
~ShapePlacement_ListOfConstraint()
{
  Clear();
}
  
        Standard_Boolean IsEmpty() const;
  
  Standard_EXPORT     void Prepend(const ShapePlacement_Constraint& I) ;
  
  Standard_EXPORT     void Prepend(const ShapePlacement_Constraint& I,ShapePlacement_ListIteratorOfListOfConstraint& theIt) ;
  
  Standard_EXPORT     void Prepend(ShapePlacement_ListOfConstraint& Other) ;
  
  Standard_EXPORT     void Append(const ShapePlacement_Constraint& I) ;
  
  Standard_EXPORT     void Append(const ShapePlacement_Constraint& I,ShapePlacement_ListIteratorOfListOfConstraint& theIt) ;
  
  Standard_EXPORT     void Append(ShapePlacement_ListOfConstraint& Other) ;
  
  Standard_EXPORT     ShapePlacement_Constraint& First() const;
  
  Standard_EXPORT     ShapePlacement_Constraint& Last() const;
  
  Standard_EXPORT     void RemoveFirst() ;
  
  Standard_EXPORT     void Remove(ShapePlacement_ListIteratorOfListOfConstraint& It) ;
  
  Standard_EXPORT     void InsertBefore(const ShapePlacement_Constraint& I,ShapePlacement_ListIteratorOfListOfConstraint& It) ;
  
  Standard_EXPORT     void InsertBefore(ShapePlacement_ListOfConstraint& Other,ShapePlacement_ListIteratorOfListOfConstraint& It) ;
  
  Standard_EXPORT     void InsertAfter(const ShapePlacement_Constraint& I,ShapePlacement_ListIteratorOfListOfConstraint& It) ;
  
  Standard_EXPORT     void InsertAfter(ShapePlacement_ListOfConstraint& Other,ShapePlacement_ListIteratorOfListOfConstraint& It) ;


friend class ShapePlacement_ListIteratorOfListOfConstraint;



protected:





private:

  
  Standard_EXPORT   ShapePlacement_ListOfConstraint(const ShapePlacement_ListOfConstraint& Other);


Standard_Address myFirst;
Standard_Address myLast;


};

#define Item ShapePlacement_Constraint
#define Item_hxx <ShapePlacement_Constraint.hxx>
#define TCollection_ListNode ShapePlacement_ListNodeOfListOfConstraint
#define TCollection_ListNode_hxx <ShapePlacement_ListNodeOfListOfConstraint.hxx>
#define TCollection_ListIterator ShapePlacement_ListIteratorOfListOfConstraint
#define TCollection_ListIterator_hxx <ShapePlacement_ListIteratorOfListOfConstraint.hxx>
#define Handle_TCollection_ListNode Handle_ShapePlacement_ListNodeOfListOfConstraint
#define TCollection_ListNode_Type_() ShapePlacement_ListNodeOfListOfConstraint_Type_()
#define TCollection_List ShapePlacement_ListOfConstraint
#define TCollection_List_hxx <ShapePlacement_ListOfConstraint.hxx>

#include <TCollection_List.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
