// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapePlacement_TypeOfEquation_HeaderFile
#define _ShapePlacement_TypeOfEquation_HeaderFile

//! Type of a Equation <br>
enum ShapePlacement_TypeOfEquation {
ShapePlacement_PLANE_PLACEMENT,
ShapePlacement_AXIS_AXIS_PLACEMENT,
ShapePlacement_LINE_PLACEMENT,
ShapePlacement_P_ANGULAR_PLACEMENT,
ShapePlacement_A_ANGULAR_PLACEMENT,
ShapePlacement_CONE_PLACEMENT,
ShapePlacement_PLANE_AXIS_PLACEMENT
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
