// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapePlacement_TypeOfConstraint_HeaderFile
#define _ShapePlacement_TypeOfConstraint_HeaderFile

//! Type of a Constraint. <br>
enum ShapePlacement_TypeOfConstraint {
ShapePlacement_ALIGN,
ShapePlacement_IN_ALIGN,
ShapePlacement_OUT_ALIGN,
ShapePlacement_PARALLELE,
ShapePlacement_IN_PARALLELE,
ShapePlacement_OUT_PARALLELE,
ShapePlacement_ANGLE,
ShapePlacement_IN_ANGLE,
ShapePlacement_OUT_ANGLE
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
