// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ShapePlacement_ListOfConstraint.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _ShapePlacement_ListIteratorOfListOfConstraint_HeaderFile
#include <ShapePlacement_ListIteratorOfListOfConstraint.hxx>
#endif
#ifndef _ShapePlacement_Constraint_HeaderFile
#include <ShapePlacement_Constraint.hxx>
#endif
#ifndef _ShapePlacement_ListNodeOfListOfConstraint_HeaderFile
#include <ShapePlacement_ListNodeOfListOfConstraint.hxx>
#endif
 

#define Item ShapePlacement_Constraint
#define Item_hxx <ShapePlacement_Constraint.hxx>
#define TCollection_ListNode ShapePlacement_ListNodeOfListOfConstraint
#define TCollection_ListNode_hxx <ShapePlacement_ListNodeOfListOfConstraint.hxx>
#define TCollection_ListIterator ShapePlacement_ListIteratorOfListOfConstraint
#define TCollection_ListIterator_hxx <ShapePlacement_ListIteratorOfListOfConstraint.hxx>
#define Handle_TCollection_ListNode Handle_ShapePlacement_ListNodeOfListOfConstraint
#define TCollection_ListNode_Type_() ShapePlacement_ListNodeOfListOfConstraint_Type_()
#define TCollection_List ShapePlacement_ListOfConstraint
#define TCollection_List_hxx <ShapePlacement_ListOfConstraint.hxx>
#include <TCollection_List.gxx>

